### ISSUE TITLE
external DLL is not nessecary

### ISSUE THREAD

**Issue by ckrueger1979** [hahndorf/ClipboardHelper#1]
It's not nessecary to create an external dll.
The trick is to find a way to reference an UWP assembly from powershell

https://stackoverflow.com/questions/45086059/how-can-i-reference-uwp-classes-in-powershell

`
$ClipboardObjectClass = 
[Windows.ApplicationModel.DataTransfer.Clipboard,Windows.ApplicationModel.DataTransfer,ContentType=WindowsRuntime] ;
$ClipboardObjectClass::ClearHistory()
`

**Comment by hahndorf** [comment]
Thank you @ckruegerkpmg, I added a PowerShell function that uses your suggestion.
